#!/usr/bin/env python3
"""Build a one-file ARC agent compatible with the official Kaggle starter.

The official ARC-AGI-3 starter only injects ``agent/my_agent.py`` into the
submission notebook. This project keeps reusable code under ``src/arc_agent``.
When the active agent imports that package, this script embeds the package as a
small deterministic zip archive and prepends a bootstrap that makes it
importable at runtime.

For agents that do not import ``arc_agent`` (including EXP-000), the source is
copied byte-for-byte so the baseline remains unchanged.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
import io
import re
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "agent" / "my_agent.py"
DEFAULT_OUTPUT = ROOT / "dist" / "my_agent.py"
PACKAGE_ROOT = ROOT / "src" / "arc_agent"

_INTERNAL_IMPORT = re.compile(r"(^|\n)\s*(?:from\s+arc_agent\b|import\s+arc_agent\b)")
_FIXED_ZIP_TIME = (1980, 1, 1, 0, 0, 0)


def _package_archive_bytes(package_root: Path = PACKAGE_ROOT) -> bytes:
    if not package_root.is_dir():
        raise FileNotFoundError(f"package directory not found: {package_root}")

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(package_root.rglob("*.py")):
            relative = path.relative_to(package_root.parent).as_posix()
            info = zipfile.ZipInfo(relative, date_time=_FIXED_ZIP_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            archive.writestr(info, path.read_bytes())
    return buffer.getvalue()


def build_standalone_source(
    source_text: str,
    *,
    force_support_bundle: bool = False,
    package_root: Path = PACKAGE_ROOT,
) -> str:
    """Return a standalone agent source string.

    ``source_text`` is returned unchanged unless it imports ``arc_agent`` or
    ``force_support_bundle`` is used. Keeping the no-import path byte-for-byte
    identical preserves EXP-000 exactly.
    """
    needs_support = force_support_bundle or bool(_INTERNAL_IMPORT.search(source_text))
    if not needs_support:
        return source_text

    bundle = _package_archive_bytes(package_root)
    encoded = base64.b64encode(bundle).decode("ascii")
    bundle_hash = hashlib.sha256(bundle).hexdigest()[:16]
    source_literal = repr(source_text)

    return f'''# Generated by scripts/build_standalone_agent.py. Do not edit this file.\nimport base64 as _base64\nimport sys as _sys\nimport tempfile as _tempfile\nfrom pathlib import Path as _Path\n\n_bundle = _base64.b64decode({encoded!r})\n_bundle_path = _Path(_tempfile.gettempdir()) / "arc_agent_support_{bundle_hash}.zip"\nif not _bundle_path.exists():\n    _bundle_path.write_bytes(_bundle)\nif str(_bundle_path) not in _sys.path:\n    _sys.path.insert(0, str(_bundle_path))\n\n_source = {source_literal}\nexec(compile(_source, "agent/my_agent.py", "exec"), globals(), globals())\n'''


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--force-support-bundle",
        action="store_true",
        help="embed src/arc_agent even when the source does not import it",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source = args.source.read_text(encoding="utf-8")
    standalone = build_standalone_source(
        source,
        force_support_bundle=args.force_support_bundle,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(standalone, encoding="utf-8")
    print(f"built standalone agent: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
